### PR TITLE
Make composer actually work

### PR DESCRIPTION
**Pull request by petski**
See commits. Please s/petski/cmanley/g in composer.json after merge.

### CODE REVIEW

**Comment by cmanley** [comment]
That won't work if it's got petsk and a release version (v1.0.0) in the URL. There's no release yet.
There's also no autoloader yet.

**Comment by petski** [comment]
You can easily create a release here: https://github.com/cmanley/PHP-Validate/releases

Regarding "petski", please see my previous comment: 

> Please s/petski/cmanley/g in composer.json after merge.

**Comment by cmanley** [comment]
What is the reason that the extensions .class.php were renamed to .php? Has it got something to do with the autoloader that composer generates? Have you confirmed that your composer.json file works?

**Comment by petski** [comment]
I renamed them from ".class.php" to ".php" so that the autoloader works out-of-the-box. There is way to specify the class-files. I can investigate that if you don't want the "rename".

I use exactly this composer file in a production project. Works like a charm.

**Comment by cmanley** [comment]
Does it work now?

**Comment by petski** [comment]
Yes, it works. But, it would be helpful if:
- you'd create a version (https://github.com/cmanley/PHP-Validate/releases), i.e. "1.0.0"
- you'd register your project at https://packagist.org/

**Comment by cmanley** [comment]
Yes, I'll create a release after some time, to make sure it's stable enough.

**Comment by petski** [comment]
Ok. In that case, can you create a version 0.9.0? (And publish it at packagist?)

**Comment by cmanley** [comment]
It's now in packagist as release 0.9.1:
https://packagist.org/packages/cmanley/php-validate
I hope it works.

**Comment by petski** [comment]
It works, and it works like a charm! Thanks!

**Pull request closed without merging**
